from django.db import models
from django.utils.functional import lazy

class Question(models.Model):
    question = models.TextField()
    create_date = models.DateTimeField('create date', auto_now_add=True)
    def __unicode__(self):
        return self.question

class Answer(models.Model):    
    description =  models.TextField()
    min_yes = models.IntegerField()
    max_yes = models.IntegerField()
    user_count = models.IntegerField(default=0)
    def __unicode__(self):
        return "%s<%s>" % (self.name, self.team)
        

CHOICE_GENDER = (('1', 'sugar daddy'),
                 ('2', 'sugar baby[female]'),
                 ('3', 'sugar mommy'),
                 ('3', 'sugar baby[male]'),)

#choices=lazy(bodystyle_choices, tuple)()
class Country(models.Model):
    cid = models.IntegerField(unique=True)
    name = models.CharField(max_length=32, unique=True)
    def __unicode__(self):
        return "%s" % (self.name)

class SugarUser(models.Model):
    fb_uid = models.IntegerField(unique=True)
    category = models.ForeignKey(Answer, null=True, blank=True)

    location = models.ForeignKey(Country, null=True) #models.IntegerField(default=0, choices=lazy(country_list, tuple)())
    gender = models.CharField(max_length=1, choices=CHOICE_GENDER)
    seeking = models.CharField(max_length=1, choices=CHOICE_GENDER)
    photo = models.CharField(max_length=255, null=True)
    description = models.TextField(null=True)
    
    featured = models.CharField(max_length=1, default="N", choices=(("Y", "YES"), ("N", "NO")))
    
    joined = models.CharField(max_length=1, default="N", choices=(("Y", "YES"), ("N", "NO")))
    create_date = models.DateTimeField('create date', auto_now_add=True)
    join_date = models.DateTimeField('join date', auto_now_add=True)
    def __unicode__(self):
        return "%s<%s>" % (self.fb_uid, self.gender)


def data_initialize():
    def _q(q):
        Question(question=q).save()
    
    def _a(a, min, max):
        Answer(description=a, min_yes=min, max_yes=max).save()

    def _c(id, name):
        Country(cid=id, name=name).save()
    
    _q("Do you take pre-Marital sex easy?")
    _q("Do you take extra-Marital sex easy?")
    _q("Is it human instinct to be attracted to beauty as it is to be attracted to wealth and power?")
    _q("Do you love to treated like a king or queen?")
    _q("Are you generous to support or care?")
    _q("Is it human nature for people to want younger and more attractive partners?")
    _q("Is it natural for younger men & women to seek out more experienced, sophisticated partners, specifically those who have the means of providing them with comforts and luxuries?")
    _q("Are you mature and rich or young but in financial difficulty?")
    _q("Are you interested in a discreet and mutually beneficial relationship?")
    _q("Are you want good living and finer things in life and also share with others?")
    
    _a("like Sugardaddy Lifestyle.", 10, 100,)
    _a("are absolutely interested in Sugardaddy Lifestyle.", 8, 9)
    _a("are probably interested in Sugardaddy Lifestyle.", 5, 7)
    _a("are probably not interested in Sugardaddy Lifestyle.", 3, 4)
    _a("are not interested in Sugardaddy Lifestyle.", 1, 2)
    _a("hate Sugardaddy Lifestyle.", -1, 0,)
    
    _c(0, "United States")
    _c(31, "Canada")
    _c(180, "United Kingdom")
    _c(1, "Afghanistan")
    _c(2, "Albania")
    _c(3, "Algeria")
    _c(4, "Andorra")
    _c(5, "Angola")
    _c(201, "Anguilla")
    _c(6, "Antigua & Barbuda")
    _c(7, "Argentina")
    _c(8, "Armenia")
    _c(196, "Aruba")
    _c(9, "Australia")
    _c(10, "Austria")
    _c(11, "Azerbaijan")
    _c(12, "Bahamas")
    _c(13, "Bahrain")
    _c(14, "Bangladesh")
    _c(15, "Barbados")
    _c(17, "Belgium")
    _c(18, "Belize")
    _c(19, "Benin")
    _c(197, "Bermuda")
    _c(20, "Bhutan")
    _c(21, "Bolivia")
    _c(22, "Bosnia and Herzegovina")
    _c(23, "Botswana")
    _c(24, "Brazil")
    _c(203, "British Indian Ocean Territory")
    _c(25, "Brunei Darussalam")
    _c(26, "Bulgaria")
    _c(27, "Burkina Faso")
    _c(28, "Burundi")
    _c(29, "Cambodia")
    _c(30, "Cameroon")
    _c(32, "Cape Verde")
    _c(204, "Cayman Islands")
    _c(33, "Central African Republic")
    _c(34, "Chad")
    _c(35, "Chile")
    _c(36, "China")
    _c(37, "Colombia")
    _c(38, "Comoros")
    _c(205, "Cook Islands")
    _c(41, "Costa Rica")
    _c(43, "Croatia")
    _c(45, "Cyprus")
    _c(46, "Czech Republic")
    _c(47, "Denmark")
    _c(48, "Djibouti")
    _c(49, "Dominica")
    _c(50, "Dominican Republic")
    _c(51, "Ecuador")
    _c(52, "Egypt")
    _c(53, "El Salvador")
    _c(54, "Equatorial Guinea")
    _c(55, "Eritrea")
    _c(56, "Estonia")
    _c(57, "Ethiopia")
    _c(236, "Europe")
    _c(206, "Falkland Islands")
    _c(207, "Faroe Islands")
    _c(208, "Federated States of Micronesia")
    _c(58, "Fiji")
    _c(59, "Finland")
    _c(60, "France")
    _c(209, "French Guiana")
    _c(210, "French Polynesia")
    _c(61, "Gabon")
    _c(62, "Gambia")
    _c(63, "Georgia")
    _c(64, "Germany")
    _c(65, "Ghana")
    _c(211, "Gibraltar")
    _c(66, "Greece")
    _c(212, "Greenland")
    _c(67, "Grenada")
    _c(213, "Guam")
    _c(68, "Guatemala")
    _c(69, "Guinea")
    _c(70, "Guinea-Bissau")
    _c(71, "Guyana")
    _c(72, "Haiti")
    _c(73, "Honduras")
    _c(74, "Hungary")
    _c(75, "Iceland")
    _c(76, "India")
    _c(77, "Indonesia")
    _c(80, "Ireland")
    _c(81, "Israel")
    _c(82, "Italy")
    _c(83, "Jamaica")
    _c(84, "Japan")
    _c(85, "Jordan")
    _c(86, "Kazakhstan")
    _c(87, "Kenya")
    _c(88, "Kiribati")
    _c(90, "Korea, South")
    _c(91, "Kuwait")
    _c(92, "Kyrgyzstan")
    _c(93, "Laos")
    _c(94, "Latvia")
    _c(95, "Lebanon")
    _c(96, "Lesotho")
    _c(97, "Liberia")
    _c(98, "Libya")
    _c(99, "Liechtenstein")
    _c(100, "Lithuania")
    _c(101, "Luxembourg")
    _c(195, "Macao SAR")
    _c(102, "Macedonia")
    _c(103, "Madagascar")
    _c(104, "Malawi")
    _c(105, "Malaysia")
    _c(106, "Maldives")
    _c(107, "Mali")
    _c(108, "Malta")
    _c(109, "Marshall Islands")
    _c(110, "Mauritania")
    _c(111, "Mauritius")
    _c(215, "Mayotte")
    _c(112, "Mexico")
    _c(113, "Moldova")
    _c(114, "Monaco")
    _c(115, "Mongolia")
    _c(217, "Montserrat")
    _c(116, "Morocco")
    _c(117, "Mozambique")
    _c(119, "Namibia")
    _c(120, "Nauru")
    _c(121, "Nepal")
    _c(122, "Netherlands")
    _c(218, "Netherlands Antilles")
    _c(219, "New Caledonia")
    _c(123, "New Zealand")
    _c(124, "Nicaragua")
    _c(125, "Niger")
    _c(126, "Nigeria")
    _c(220, "Niue")
    _c(221, "Norfolk Island")
    _c(222, "Northern Mariana Islands")
    _c(127, "Norway")
    _c(128, "Oman")
    _c(129, "Pakistan")
    _c(130, "Palau")
    _c(235, "Palestine")
    _c(131, "Panama")
    _c(132, "Papua New Guinea")
    _c(133, "Paraguay")
    _c(134, "Peru")
    _c(135, "Philippines")
    _c(223, "Pitcairn")
    _c(136, "Poland")
    _c(137, "Portugal")
    _c(191, "Puerto Rico")
    _c(138, "Qatar")
    _c(224, "Reunion")
    _c(139, "Romania")
    _c(140, "Russia")
    _c(141, "Rwanda")
    _c(144, "Saint Vincent & the Grenadines")
    _c(145, "Samoa")
    _c(146, "San Marino")
    _c(147, "Sao Tome and Principe")
    _c(148, "Saudi Arabia")
    _c(149, "Senegal")
    _c(187, "Serbia and Montenegro (former Yugoslavia)")
    _c(150, "Seychelles")
    _c(151, "Sierra Leone")
    _c(152, "Singapore")
    _c(153, "Slovakia")
    _c(154, "Slovenia")
    _c(155, "Solomon Islands")
    _c(156, "Somalia")
    _c(157, "South Africa")
    _c(226, "South Georgia")
    _c(158, "Spain")
    _c(159, "Sri Lanka")
    _c(142, "St. Kitts and Nevis")
    _c(143, "St. Lucia")
    _c(229, "St. Pierre and Miquelon")
    _c(161, "Suriname")
    _c(162, "Swaziland")
    _c(163, "Sweden")
    _c(164, "Switzerland")
    _c(166, "Taiwan")
    _c(167, "Tajikistan")
    _c(168, "Tanzania")
    _c(169, "Thailand")
    _c(170, "Togo")
    _c(230, "Tokelau")
    _c(171, "Tonga")
    _c(172, "Trinidad & Tobago")
    _c(173, "Tunisia")
    _c(174, "Turkey")
    _c(175, "Turkmenistan")
    _c(231, "Turks and Caicos Islands")
    _c(176, "Tuvalu")
    _c(177, "Uganda")
    _c(178, "Ukraine")
    _c(179, "United Arab Emirates")
    _c(181, "Uruguay")
    _c(182, "Uzbekistan")
    _c(183, "Vanuatu")
    _c(184, "Venezuela")
    _c(185, "Vietnam")
    _c(232, "Virgin Islands (U.K.)")
    _c(233, "Virgin Islands (U.S.)")
    _c(234, "Wallis and Futuna Islands")
    _c(186, "Yemen")
    _c(188, "Zaire")
    _c(189, "Zambia")

    
    