//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by BTSMonitor.rc
//
#define IDI_WARNING_VIEW_HC             5
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDD_RUNTIME_WARNING             101
#define IDS_FIND_CAMERA                 101
#define IDS_RIBBON_FIND_CAMERA          102
#define IDP_SOCKETS_INIT_FAILED         104
#define IDB_WRITESMALL                  110
#define IDB_WRITELARGE                  111
#define IDB_MAIN                        112
#define IDB_BUTTONS                     113
#define IDB_FILELARGE                   114
#define IDB_FILESMALL                   115
#define IDR_POPUP_EDIT                  119
#define ID_STATUSBAR_PANE1              120
#define ID_STATUSBAR_PANE2              121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define IDR_BTSMonitorTYPE              130
#define ID_WINDOW_MANAGER               131
#define IDS_WINDOWS_MANAGER             132
#define ID_VIEW_FILEVIEW                133
#define ID_VIEW_CLASSVIEW               134
#define ID_PROPERTIES                   135
#define ID_OPEN                         136
#define ID_OPEN_WITH                    137
#define ID_DUMMY_COMPILE                138
#define ID_CLASS_ADD_MEMBER_FUNCTION    139
#define ID_CLASS_ADD_MEMBER_VARIABLE    140
#define ID_CLASS_DEFINITION             141
#define ID_CLASS_PROPERTIES             142
#define ID_NEW_FOLDER                   143
#define ID_SORT_MENU                    144
#define ID_SORTING_GROUPBYTYPE          145
#define ID_SORTING_SORTALPHABETIC       146
#define ID_SORTING_SORTBYTYPE           147
#define ID_SORTING_SORTBYACCESS         148
#define IDR_PASTE_MENU                  151
#define IDR_WINDOWS_MENU                152
#define IDS_FILE_VIEW                   155
#define IDS_CLASS_VIEW                  156
#define IDI_FILE_VIEW                   161
#define IDI_FILE_VIEW_HC                162
#define IDI_CLASS_VIEW                  163
#define IDI_CLASS_VIEW_HC               164
#define IDR_EXPLORER                    169
#define IDB_EXPLORER_24                 170
#define IDR_SORT                        171
#define IDB_SORT_24                     172
#define IDR_POPUP_SORT                  173
#define IDR_POPUP_EXPLORER              174
#define IDB_FILE_VIEW                   175
#define IDB_FILE_VIEW_24                176
#define IDB_CLASS_VIEW                  177
#define IDB_CLASS_VIEW_24               178
#define IDR_MENU_IMAGES                 179
#define IDB_MENU_IMAGES_24              180
#define ID_TOOLS_MACRO                  181
#define IDB_CAMERA_VIEW                 181
#define IDB_SYSTEMLARGE                 182
#define IDB_SYSTEMSMALL                 183
#define IDB_MONITOR_LARGE               184
#define IDB_WRITESMALL1                 185
#define IDB_MONITOR_SMALL               185
#define IDR_THEME_MENU                  200
#define ID_SET_STYLE                    201
#define ID_VIEW_APPLOOK_WIN_2000        210
#define ID_VIEW_APPLOOK_OFF_XP          211
#define ID_VIEW_APPLOOK_WIN_XP          212
#define ID_VIEW_APPLOOK_OFF_2003        213
#define ID_VIEW_APPLOOK_VS_2005         214
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   215
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  216
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 217
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   218
#define IDS_RIBBON_FILE                 260
#define IDS_RIBBON_NEW                  262
#define IDS_RIBBON_OPEN                 263
#define IDS_RIBBON_SAVE                 264
#define IDS_RIBBON_SAVEAS               265
#define IDS_RIBBON_PRINT                266
#define IDS_RIBBON_PRINT_LABEL          267
#define IDS_RIBBON_PRINT_QUICK          268
#define IDS_RIBBON_PRINT_PREVIEW        269
#define IDS_RIBBON_PRINT_SETUP          270
#define IDS_RIBBON_CLOSE                271
#define IDS_RIBBON_RECENT_DOCS          272
#define IDS_RIBBON_EXIT                 273
#define IDS_RIBBON_HOME                 274
#define IDS_RIBBON_CLIPBOARD            275
#define IDS_RIBBON_PASTE                276
#define IDS_RIBBON_CUT                  277
#define IDS_RIBBON_COPY                 278
#define IDS_RIBBON_SELECTALL            279
#define IDS_RIBBON_WINDOW               284
#define IDS_RIBBON_WINDOWS              285
#define IDS_RIBBON_STYLE                286
#define IDS_RIBBON_STYLE_TIP            287
#define IDS_RIBBON_STYLE_DESC           288
#define IDS_RIBBON_STATUSBAR            289
#define IDS_RIBBON_VIEW                 290
#define IDS_EXPLORER                    305
#define IDS_EDIT_MENU                   306
#define ID_VIEW_WARNING                 310
#define ID_VIEW_CAMERA                  311
#define IDI_WARNING_VIEW                312
#define IDD_CRITICAL_WARNING            314
#define IDD_GENERAL_WARNING             315
#define IDD_DLG_FIND                    316
#define IDD_DLG_LOGIN                   317
#define IDI_UNKNOW                      318
#define IDI_UNKNOWN                     318
#define IDI_UNACK                       319
#define IDI_ACK                         320
#define IDC_LST_RUNTIME_WARNING         1000
#define IDC_LIST_GENERAL_WARNING        1000
#define IDC_LIST_CRITICAL_WARNING       1000
#define IDC_FINDSTR                     1001
#define IDC_EDIT_USER                   1002
#define IDC_EDIT_PWD                    1003
#define IDC_EDIT_SERVER                 1004
#define ID_WRITE_PASTEASHYPERLINK       32770
#define ID_FIND_CAMERA                  32771
#define ID_VV1                          32781
#define ID_VV4                          32782
#define ID_VV6                          32783
#define ID_VV8                          32784
#define ID_VV9                          32785
#define ID_VV16                         32786
#define ID_VV25                         32787

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        321
#define _APS_NEXT_COMMAND_VALUE         32788
#define _APS_NEXT_CONTROL_VALUE         1004
#define _APS_NEXT_SYMED_VALUE           312
#endif
#endif
