<?php
global $cross_cfg,$common_event_cfg;
//应用内容配置
$cross_cfg = array(
	//灭绝师太
	array(
		"img"=>SITE_ROOT."conf/res/miejue.jpg",//人物图片 
		"time"=>array(//具体时代
			array(
				"name"=>"明朝",//时代名称
				"people"=>array(//人物配置 
					array(
						"name"=>"灭绝师太",//人物名称
						"event"=>array(//特定人物事件
							"拿着倚天剑对着@{username}说：秃驴，你Y再不跟我回峨嵋，我就跟你去少林。",
							"对@{username}说：为师教你上，中，下三套剑法，你为何一定要学下剑？",
							),
					),
				),
			),
		),
	),
	//观音：
	array(
		"img"=>SITE_ROOT."conf/res/guanyin.gif",//人物图片 
		"time"=>array(//具体时代
			array(
				"name"=>"",//时代名称
				"people"=>array(//人物配置 
					array(
						"name"=>"观音菩萨",//人物名称
						"event"=>array(//特定人物事件
							"对@{username}说：呔，孽畜，本座一日不看住于你，你就下界为跃，为祸人间，今日我就收了你！",
							),
					),
				),
			),
			array(
				"name"=>"",//时代名称
				"people"=>array(//人物配置 
					array(
						"name"=>"千手观音",//人物名称
						"event"=>array(//特定人物事件
							"对@{username}说：亲，咱们来打赌吧！ @{username}：好啊~~输了怎么办？  千手观音：输了就被对方打耳光好啦~",
							),
					),
				),
			),
		),
	),
	//唐僧：
	array(
		"img"=>SITE_ROOT."conf/res/tangshen.gif",//人物图片 
		"time"=>array(//具体时代
			array(
				"name"=>"唐朝",//时代名称
				"people"=>array(//人物配置 
					array(
						"name"=>"唐僧",//人物名称
						"event"=>array(//特定人物事件
							"参加《非诚勿扰》，24灯全亮。理由 ： 1.公务员； 2.皇上兄弟，后台最硬 3.精通梵文等外语 4.长得帅 5.最关键一点：有宝马！",
							"历经九九八十一难，终于见到了如来！如来问：你带U盘了吗？当场晕倒",
							"大早上看见悟空暴死在地上，八戒和沙僧啜泣不止，忙问：悟空怎么死了！八戒边哭边说到：“师傅，你昨晚说梦话念了一晚上紧箍咒……”",
							),
					),
				),
			),
		),
	),
	//大乔：
	array(
		"img"=>SITE_ROOT."conf/res/daqiao.gif",//人物图片 
		"time"=>array(//具体时代
			array(
				"name"=>"三国",//时代名称
				"people"=>array(//人物配置 
					array(
						"name"=>"大乔",//人物名称
						"event"=>array(//特定人物事件
							"和@{username}比体重说：每一次量体重，轻了就对自己说：瘦了。重了就对自己说：胸部大了...",
							"正向@{username}发牢骚：我一不高兴就喜欢吃东西，一吃东西就发胖，一发胖我就很不高兴...",
							"拿着镜子对@{username}说：虽然你长得很有气质，但比起凤姐，你还差得远了！",
							),
					),
				),
			),
		),
	),
	//小乔：
	array(
		"img"=>SITE_ROOT."conf/res/xiaoqiao.gif",//人物图片 
		"time"=>array(//具体时代
			array(
				"name"=>"三国",//时代名称
				"people"=>array(//人物配置 
					array(
						"name"=>"小乔",//人物名称
						"event"=>array(//特定人物事件
							"和@{username}比体重说：每一次量体重，轻了就对自己说：瘦了。重了就对自己说：胸部大了...",
							"正向@{username}发牢骚：我一不高兴就喜欢吃东西，一吃东西就发胖，一发胖我就很不高兴...",
							"对着@{username}抛了个媚眼：人在江湖漂，哪能不挨刀。",
							),
					),
				),
			),
		),
	),
	//孙尚香：
	array(
		"img"=>SITE_ROOT."conf/res/sunshangxiang.gif",//人物图片 
		"time"=>array(//具体时代
			array(
				"name"=>"三国",//时代名称
				"people"=>array(//人物配置 
					array(
						"name"=>"孙尚香",//人物名称
						"event"=>array(//特定人物事件
							"和@{username}比体重说：每一次量体重，轻了就对自己说：瘦了。重了就对自己说：胸部大了...",
							"正向@{username}发牢骚：我一不高兴就喜欢吃东西，一吃东西就发胖，一发胖我就很不高兴...",
							),
					),
				),
			),
		),
	),
	//貂蝉：
	array(
		"img"=>SITE_ROOT."conf/res/diaochan.gif",//人物图片 
		"time"=>array(//具体时代
			array(
				"name"=>"三国",//时代名称
				"people"=>array(//人物配置 
					array(
						"name"=>"貂蝉",//人物名称
						"event"=>array(//特定人物事件
							"和@{username}比体重说：每一次量体重，轻了就对自己说：瘦了。重了就对自己说：胸部大了...",
							"正向@{username}发牢骚：我一不高兴就喜欢吃东西，一吃东西就发胖，一发胖我就很不高兴...",
							),
					),
				),
			),
		),
	),
	//孙二娘：
	array(
		"img"=>SITE_ROOT."conf/res/sunerliang.gif",//人物图片 
		"time"=>array(//具体时代
			array(
				"name"=>"",//时代名称
				"people"=>array(//人物配置 
					array(
						"name"=>"孙二娘",//人物名称
						"event"=>array(//特定人物事件
							"和@{username}比体重说：每一次量体重，轻了就对自己说：瘦了。重了就对自己说：胸部大了...",
							"正向@{username}发牢骚：我一不高兴就喜欢吃东西，一吃东西就发胖，一发胖我就很不高兴...",
							"对@{username}yu :我也想做一个优雅的淑女，是生活把老娘逼成了泼妇",
							),
					),
				),
			),
		),
	),
	//佟湘玉：
	array(
		"img"=>SITE_ROOT."conf/res/tongxiangyu.jpg",//人物图片 
		"time"=>array(//具体时代
			array(
				"name"=>"",//时代名称
				"people"=>array(//人物配置 
					array(
						"name"=>"佟湘玉",//人物名称
						"event"=>array(//特定人物事件
							"和@{username}比体重说：每一次量体重，轻了就对自己说：瘦了。重了就对自己说：胸部大了...",
							"正向@{username}发牢骚：我一不高兴就喜欢吃东西，一吃东西就发胖，一发胖我就很不高兴...",
							"对@{username}yu :我也想做一个优雅的淑女，是生活把老娘逼成了泼妇",
							),
					),
				),
			),
		),
	),
	//武则天：
	array(
		"img"=>SITE_ROOT."conf/res/wuzetian.jpg",//人物图片 
		"time"=>array(//具体时代
			array(
				"name"=>"",//时代名称
				"people"=>array(//人物配置 
					array(
						"name"=>"武则天",//人物名称
						"event"=>array(//特定人物事件
							"和@{username}比体重说：每一次量体重，轻了就对自己说：瘦了。重了就对自己说：胸部大了...",
							"正向@{username}发牢骚：我一不高兴就喜欢吃东西，一吃东西就发胖，一发胖我就很不高兴...",
							),
					),
				),
			),
		),
	),
	//白娘子：
	array(
		"img"=>SITE_ROOT."conf/res/bailiangzi.jpg",//人物图片 
		"time"=>array(//具体时代
			array(
				"name"=>"",//时代名称
				"people"=>array(//人物配置 
					array(
						"name"=>"白素贞",//人物名称
						"event"=>array(//特定人物事件
							"和@{username}比体重说：每一次量体重，轻了就对自己说：瘦了。重了就对自己说：胸部大了...",
							"正向@{username}发牢骚：我一不高兴就喜欢吃东西，一吃东西就发胖，一发胖我就很不高兴...",
							),
					),
				),
			),
		),
	),
	//嫦娥：
	array(
		"img"=>SITE_ROOT."conf/res/change.gif",//人物图片 
		"time"=>array(//具体时代
			array(
				"name"=>"",//时代名称
				"people"=>array(//人物配置 
					array(
						"name"=>"嫦娥",//人物名称
						"event"=>array(//特定人物事件
							"和@{username}比体重说：每一次量体重，轻了就对自己说：瘦了。重了就对自己说：胸部大了...",
							"正向@{username}发牢骚：我一不高兴就喜欢吃东西，一吃东西就发胖，一发胖我就很不高兴...",
							),
					),
				),
			),
		),
	),
	//陈圆圆：
	array(
		"img"=>SITE_ROOT."conf/res/chenyuanyuan.jpg",//人物图片 
		"time"=>array(//具体时代
			array(
				"name"=>"",//时代名称
				"people"=>array(//人物配置 
					array(
						"name"=>"陈圆圆",//人物名称
						"event"=>array(//特定人物事件
							"和@{username}比体重说：每一次量体重，轻了就对自己说：瘦了。重了就对自己说：胸部大了...",
							"正向@{username}发牢骚：我一不高兴就喜欢吃东西，一吃东西就发胖，一发胖我就很不高兴...",
							),
					),
				),
			),
		),
	),
	//郭芙蓉：
	array(
		"img"=>SITE_ROOT."conf/res/guofurong.gif",//人物图片 
		"time"=>array(//具体时代
			array(
				"name"=>"",//时代名称
				"people"=>array(//人物配置 
					array(
						"name"=>"郭芙蓉",//人物名称
						"event"=>array(//特定人物事件
							"和@{username}比体重说：每一次量体重，轻了就对自己说：瘦了。重了就对自己说：胸部大了...",
							"正向@{username}发牢骚：我一不高兴就喜欢吃东西，一吃东西就发胖，一发胖我就很不高兴...",
							"对@{username}yu :我也想做一个优雅的淑女，是生活把老娘逼成了泼妇",
							),
					),
				),
			),
		),
	),
	//红娘：
	array(
		"img"=>SITE_ROOT."conf/res/hongliang.jpg",//人物图片 
		"time"=>array(//具体时代
			array(
				"name"=>"",//时代名称
				"people"=>array(//人物配置 
					array(
						"name"=>"红娘",//人物名称
						"event"=>array(//特定人物事件
							"和@{username}比体重说：每一次量体重，轻了就对自己说：瘦了。重了就对自己说：胸部大了...",
							"正向@{username}发牢骚：我一不高兴就喜欢吃东西，一吃东西就发胖，一发胖我就很不高兴...",
							),
					),
				),
			),
		),
	),
	//穆桂英：
	array(
		"img"=>SITE_ROOT."conf/res/miaoguiying.jpg",//人物图片 
		"time"=>array(//具体时代
			array(
				"name"=>"",//时代名称
				"people"=>array(//人物配置 
					array(
						"name"=>"穆桂英",//人物名称
						"event"=>array(//特定人物事件
							"和@{username}比体重说：每一次量体重，轻了就对自己说：瘦了。重了就对自己说：胸部大了...",
							"正向@{username}发牢骚：我一不高兴就喜欢吃东西，一吃东西就发胖，一发胖我就很不高兴...",
							),
					),
				),
			),
		),
	),
	//扈三娘：
	array(
		"img"=>SITE_ROOT."conf/res/sanliang.gif",//人物图片 
		"time"=>array(//具体时代
			array(
				"name"=>"",//时代名称
				"people"=>array(//人物配置 
					array(
						"name"=>"扈三娘",//人物名称
						"event"=>array(//特定人物事件
							"和@{username}比体重说：每一次量体重，轻了就对自己说：瘦了。重了就对自己说：胸部大了...",
							"正向@{username}发牢骚：我一不高兴就喜欢吃东西，一吃东西就发胖，一发胖我就很不高兴...",
							"对@{username}yu :我也想做一个优雅的淑女，是生活把老娘逼成了泼妇",
							),
					),
				),
			),
		),
	),
	//小龙女：
	array(
		"img"=>SITE_ROOT."conf/res/xiaolongnv.jpg",//人物图片 
		"time"=>array(//具体时代
			array(
				"name"=>"",//时代名称
				"people"=>array(//人物配置 
					array(
						"name"=>"小龙女",//人物名称
						"event"=>array(//特定人物事件
							"和@{username}比体重说：每一次量体重，轻了就对自己说：瘦了。重了就对自己说：胸部大了...",
							"正向@{username}发牢骚：我一不高兴就喜欢吃东西，一吃东西就发胖，一发胖我就很不高兴...",
							),
					),
				),
			),
		),
	),
	//孝庄：
	array(
		"img"=>SITE_ROOT."conf/res/xiaozhuang.jpg",//人物图片 
		"time"=>array(//具体时代
			array(
				"name"=>"",//时代名称
				"people"=>array(//人物配置 
					array(
						"name"=>"孝庄",//人物名称
						"event"=>array(//特定人物事件
							"和@{username}比体重说：每一次量体重，轻了就对自己说：瘦了。重了就对自己说：胸部大了...",
							"正向@{username}发牢骚：我一不高兴就喜欢吃东西，一吃东西就发胖，一发胖我就很不高兴...",
							),
					),
				),
			),
		),
	),
	//西施：
	array(
		"img"=>SITE_ROOT."conf/res/xishi.jpg",//人物图片 
		"time"=>array(//具体时代
			array(
				"name"=>"",//时代名称
				"people"=>array(//人物配置 
					array(
						"name"=>"西施",//人物名称
						"event"=>array(//特定人物事件
							"和@{username}比体重说：每一次量体重，轻了就对自己说：瘦了。重了就对自己说：胸部大了...",
							"正向@{username}发牢骚：我一不高兴就喜欢吃东西，一吃东西就发胖，一发胖我就很不高兴...",
							),
					),
				),
			),
		),
	),
	//杨贵妃：
	array(
		"img"=>SITE_ROOT."conf/res/yangguifei.jpg",//人物图片 
		"time"=>array(//具体时代
			array(
				"name"=>"",//时代名称
				"people"=>array(//人物配置 
					array(
						"name"=>"杨贵妃",//人物名称
						"event"=>array(//特定人物事件
							"和@{username}比体重说：每一次量体重，轻了就对自己说：瘦了。重了就对自己说：胸部大了...",
							"正向@{username}发牢骚：我一不高兴就喜欢吃东西，一吃东西就发胖，一发胖我就很不高兴...",
							"对@{username}说：我脱一点就能当贵妃，而你脱光了只会被抓起来。",
						),
					),
				),
			),
		),
	),
	//甄姬：
	array(
		"img"=>SITE_ROOT."conf/res/yiji.gif",//人物图片 
		"time"=>array(//具体时代
			array(
				"name"=>"",//时代名称
				"people"=>array(//人物配置 
					array(
						"name"=>"甄姬",//人物名称
						"event"=>array(//特定人物事件
							"和@{username}比体重说：每一次量体重，轻了就对自己说：瘦了。重了就对自己说：胸部大了...",
							"正向@{username}发牢骚：我一不高兴就喜欢吃东西，一吃东西就发胖，一发胖我就很不高兴...",
							),
					),
				),
			),
		),
	),
	//周芷若：
	array(
		"img"=>SITE_ROOT."conf/res/zhouzhiruo.jpg",//人物图片 
		"time"=>array(//具体时代
			array(
				"name"=>"",//时代名称
				"people"=>array(//人物配置 
					array(
						"name"=>"周芷若",//人物名称
						"event"=>array(//特定人物事件
							"和@{username}比体重说：每一次量体重，轻了就对自己说：瘦了。重了就对自己说：胸部大了...",
							"正向@{username}发牢骚：我一不高兴就喜欢吃东西，一吃东西就发胖，一发胖我就很不高兴...",
							),
					),
				),
			),
		),
	),
	//祝无双：
	array(
		"img"=>SITE_ROOT."conf/res/zhuwushuang.jpg",//人物图片 
		"time"=>array(//具体时代
			array(
				"name"=>"",//时代名称
				"people"=>array(//人物配置 
					array(
						"name"=>"祝无双",//人物名称
						"event"=>array(//特定人物事件
							"和@{username}比体重说：每一次量体重，轻了就对自己说：瘦了。重了就对自己说：胸部大了...",
							"正向@{username}发牢骚：我一不高兴就喜欢吃东西，一吃东西就发胖，一发胖我就很不高兴...",
							"对@{username}yu :我也想做一个优雅的淑女，是生活把老娘逼成了泼妇",
							),
					),
				),
			),
		),
	),
	//曹操：
	array(
		"img"=>SITE_ROOT."conf/res/caocao.gif",//人物图片 
		"time"=>array(//具体时代
			array(
				"name"=>"三国",//时代名称
				"people"=>array(//人物配置 
					array(
						"name"=>"曹操",//人物名称
						"event"=>array(//特定人物事件
							"对@{username}说：你本是一匹狼，却天生一副羊的心肠，而这个天下，是狼的天下。",
							"对@{username}说：英雄你来当。小人，我来。",
						),
					),
				),
			),
		),
	),
	//东方不败：
	array(
		"img"=>SITE_ROOT."conf/res/dongfangbubai.jpg",//人物图片 
		"time"=>array(//具体时代
			array(
				"name"=>"",//时代名称
				"people"=>array(//人物配置 
					array(
						"name"=>"东方不败",//人物名称
						"event"=>array(//特定人物事件
							),
					),
				),
			),
		),
	),
	//二郎神：
	array(
		"img"=>SITE_ROOT."conf/res/erlangshen.jpg",//人物图片 
		"time"=>array(//具体时代
			array(
				"name"=>"",//时代名称
				"people"=>array(//人物配置 
					array(
						"name"=>"二郎神",//人物名称
						"event"=>array(//特定人物事件
						"总找不到女友，无奈去算命。算命师：你前半生注定没有女人。突然眼睛一亮：后半生呢？算命师说：后半生你就习惯了...",		
						),
					),
				),
			),
		),
	),
	//关羽：
	array(
		"img"=>SITE_ROOT."conf/res/guanyu.gif",//人物图片 
		"time"=>array(//具体时代
			array(
				"name"=>"",//时代名称
				"people"=>array(//人物配置 
					array(
						"name"=>"关羽",//人物名称
						"event"=>array(//特定人物事件
							"正跟张飞，刘备桃园结义，拜关二爷呢！",
						),
					),
				),
			),
		),
	),
	//林冲：
	array(
		"img"=>SITE_ROOT."conf/res/linchong.gif",//人物图片 
		"time"=>array(//具体时代
			array(
				"name"=>"",//时代名称
				"people"=>array(//人物配置 
					array(
						"name"=>"林冲",//人物名称
						"event"=>array(//特定人物事件
							),
					),
				),
			),
		),
	),
	//刘备：
	array(
		"img"=>SITE_ROOT."conf/res/liubei.gif",//人物图片 
		"time"=>array(//具体时代
			array(
				"name"=>"",//时代名称
				"people"=>array(//人物配置 
					array(
						"name"=>"刘备",//人物名称
						"event"=>array(//特定人物事件
							),
					),
				),
			),
		),
	),
	//李逍遥：
	array(
		"img"=>SITE_ROOT."conf/res/lixiaoyao.jpg",//人物图片 
		"time"=>array(//具体时代
			array(
				"name"=>"",//时代名称
				"people"=>array(//人物配置 
					array(
						"name"=>"李逍遥",//人物名称
						"event"=>array(//特定人物事件
							),
					),
				),
			),
		),
	),
	//吕布：
	array(
		"img"=>SITE_ROOT."conf/res/lubu.jpg",//人物图片 
		"time"=>array(//具体时代
			array(
				"name"=>"",//时代名称
				"people"=>array(//人物配置 
					array(
						"name"=>"吕布",//人物名称
						"event"=>array(//特定人物事件
							),
					),
				),
			),
		),
	),
	//鲁智深：
	array(
		"img"=>SITE_ROOT."conf/res/luzhishen.gif",//人物图片 
		"time"=>array(//具体时代
			array(
				"name"=>"",//时代名称
				"people"=>array(//人物配置 
					array(
						"name"=>"鲁智深",//人物名称
						"event"=>array(//特定人物事件
							),
					),
				),
			),
		),
	),
	//孟婆：
	array(
		"img"=>SITE_ROOT."conf/res/mengpo.jpg",//人物图片 
		"time"=>array(//具体时代
			array(
				"name"=>"",//时代名称
				"people"=>array(//人物配置 
					array(
						"name"=>"孟婆",//人物名称
						"event"=>array(//特定人物事件
								"笑眯眯地看着@{username}：欠你这么多钱怪不好意思的，请你喝碗孟婆汤吧。",
							),
					),
				),
			),
		),
	),
	//司马懿：
	array(
		"img"=>SITE_ROOT."conf/res/simayi.gif",//人物图片 
		"time"=>array(//具体时代
			array(
				"name"=>"",//时代名称
				"people"=>array(//人物配置 
					array(
						"name"=>"司马懿",//人物名称
						"event"=>array(//特定人物事件
							),
					),
				),
			),
		),
	),
	//宋江：
	array(
		"img"=>SITE_ROOT."conf/res/songjiang.gif",//人物图片 
		"time"=>array(//具体时代
			array(
				"name"=>"",//时代名称
				"people"=>array(//人物配置 
					array(
						"name"=>"宋江",//人物名称
						"event"=>array(//特定人物事件
							),
					),
				),
			),
		),
	),
	//孙权：
	array(
		"img"=>SITE_ROOT."conf/res/sunquan.gif",//人物图片 
		"time"=>array(//具体时代
			array(
				"name"=>"",//时代名称
				"people"=>array(//人物配置 
					array(
						"name"=>"孙权",//人物名称
						"event"=>array(//特定人物事件
							),
					),
				),
			),
		),
	),
	//唐玉小宝：
	array(
		"img"=>SITE_ROOT."conf/res/tangyuxiaobao.jpg",//人物图片 
		"time"=>array(//具体时代
			array(
				"name"=>"",//时代名称
				"people"=>array(//人物配置 
					array(
						"name"=>"唐玉小宝",//人物名称
						"event"=>array(//特定人物事件
							),
					),
				),
			),
		),
	),
	//韦小宝：
	array(
		"img"=>SITE_ROOT."conf/res/weixiaobao.jpg",//人物图片 
		"time"=>array(//具体时代
			array(
				"name"=>"",//时代名称
				"people"=>array(//人物配置 
					array(
						"name"=>"韦小宝",//人物名称
						"event"=>array(//特定人物事件
							),
					),
				),
			),
		),
	),
	//武松：
	array(
		"img"=>SITE_ROOT."conf/res/wusong.gif",//人物图片 
		"time"=>array(//具体时代
			array(
				"name"=>"",//时代名称
				"people"=>array(//人物配置 
					array(
						"name"=>"武松",//人物名称
						"event"=>array(//特定人物事件
						"总找不到女友，无奈去算命。算命师：你前半生注定没有女人。突然眼睛一亮：后半生呢？算命师说：后半生你就习惯了...",
						"和@{username}一起渴洒，说道：喝白酒三斤，我绝对没感觉，因为喝一斤半就已经喝死了。",		
						),
					),
				),
			),
		),
	),
	//孝天犬：
	array(
		"img"=>SITE_ROOT."conf/res/xiaotianquan.jpg",//人物图片 
		"time"=>array(//具体时代
			array(
				"name"=>"",//时代名称
				"people"=>array(//人物配置 
					array(
						"name"=>"孝天犬",//人物名称
						"event"=>array(//特定人物事件
							),
					),
				),
			),
		),
	),
	//赵子龙：
	array(
		"img"=>SITE_ROOT."conf/res/zhaoyun.gif",//人物图片 
		"time"=>array(//具体时代
			array(
				"name"=>"",//时代名称
				"people"=>array(//人物配置 
					array(
						"name"=>"赵子龙",//人物名称
						"event"=>array(//特定人物事件
							),
					),
				),
			),
		),
	),
	//张飞：
	array(
		"img"=>SITE_ROOT."conf/res/zhengfei.gif",//人物图片 
		"time"=>array(//具体时代
			array(
				"name"=>"",//时代名称
				"people"=>array(//人物配置 
					array(
						"name"=>"张飞",//人物名称
						"event"=>array(//特定人物事件
							),
					),
				),
			),
		),
	),
	//周瑜：
	array(
		"img"=>SITE_ROOT."conf/res/zhouyu.gif",//人物图片 
		"time"=>array(//具体时代
			array(
				"name"=>"",//时代名称
				"people"=>array(//人物配置 
					array(
						"name"=>"周瑜",//人物名称
						"event"=>array(//特定人物事件
						"对@{username}说：其实我是一个天才，只可惜天妒英才！",
							),
					),
				),
			),
		),
	),
	//诸葛亮：
	array(
		"img"=>SITE_ROOT."conf/res/zhugeliang.gif",//人物图片 
		"time"=>array(//具体时代
			array(
				"name"=>"",//时代名称
				"people"=>array(//人物配置 
					array(
						"name"=>"诸葛亮",//人物名称
						"event"=>array(//特定人物事件
							),
					),
				),
			),
		),
	),
	//阿珂：
	array(
		"img"=>SITE_ROOT."conf/res/meinv7.jpg",//人物图片 
		"time"=>array(//具体时代
			array(
				"name"=>"",//时代名称
				"people"=>array(//人物配置 
					array(
						"name"=>"阿珂",//人物名称
						"event"=>array(//特定人物事件
							"和@{username}比体重说：每一次量体重，轻了就对自己说：瘦了。重了就对自己说：胸部大了...",
							"正向@{username}发牢骚：我一不高兴就喜欢吃东西，一吃东西就发胖，一发胖我就很不高兴...",	
						),
					),
				),
			),
		),
	),
	//白居易、苏东坡：
	array(
		"img"=>SITE_ROOT."conf/res/meinv2.gif",//人物图片 
		"time"=>array(//具体时代
			array(
				"name"=>"",//时代名称
				"people"=>array(//人物配置 
					array(
						"name"=>"白居易",//人物名称
						"event"=>array(//特定人物事件
							),
					),
					array(
						"name"=>"苏东坡",//人物名称
						"event"=>array(//特定人物事件
							),
					),
				),
			),
		),
	),
	//包拯：
	array(
		"img"=>SITE_ROOT."conf/res/guanye.jpg",//人物图片 
		"time"=>array(//具体时代
			array(
				"name"=>"",//时代名称
				"people"=>array(//人物配置 
					array(
						"name"=>"包拯",//人物名称
						"event"=>array(//特定人物事件
							),
					),
				),
			),
		),
	),
	//段誉：
	array(
		"img"=>SITE_ROOT."conf/res/shaoye.jpg",//人物图片 
		"time"=>array(//具体时代
			array(
				"name"=>"",//时代名称
				"people"=>array(//人物配置 
					array(
						"name"=>"段誉",//人物名称
						"event"=>array(//特定人物事件
							),
					),
				),
			),
		),
	),
	//郭靖、张无忌：
	array(
		"img"=>SITE_ROOT."conf/res/jinyiwei3.jpg",//人物图片 
		"time"=>array(//具体时代
			array(
				"name"=>"",//时代名称
				"people"=>array(//人物配置 
					array(
						"name"=>"郭靖",//人物名称
						"event"=>array(//特定人物事件
							),
					),
					array(
						"name"=>"张无忌",//人物名称
						"event"=>array(//特定人物事件
							),
					),
				),
			),
		),
	),
	//郭襄：
	array(
		"img"=>SITE_ROOT."conf/res/wait.jpg",//人物图片 
		"time"=>array(//具体时代
			array(
				"name"=>"",//时代名称
				"people"=>array(//人物配置 
					array(
						"name"=>"郭襄",//人物名称
						"event"=>array(//特定人物事件
							"和@{username}比体重说：每一次量体重，轻了就对自己说：瘦了。重了就对自己说：胸部大了...",
							"正向@{username}发牢骚：我一不高兴就喜欢吃东西，一吃东西就发胖，一发胖我就很不高兴...",
							),
					),
				),
			),
		),
	),
	//花满楼、花无缺、楚留香：
	array(
		"img"=>SITE_ROOT."conf/res/gongzi2.jpg",//人物图片 
		"time"=>array(//具体时代
			array(
				"name"=>"",//时代名称
				"people"=>array(//人物配置 
					array(
						"name"=>"花满楼",//人物名称
						"event"=>array(//特定人物事件
							),
					),
					array(
						"name"=>"花无缺",//人物名称
						"event"=>array(//特定人物事件
							),
					),
					array(
						"name"=>"楚留香",//人物名称
						"event"=>array(//特定人物事件
							),
					),
				),
			),
		),
	),
	//黄药师：
	array(
		"img"=>SITE_ROOT."conf/res/chuixiao.jpg",//人物图片 
		"time"=>array(//具体时代
			array(
				"name"=>"",//时代名称
				"people"=>array(//人物配置 
					array(
						"name"=>"黄药师",//人物名称
						"event"=>array(//特定人物事件
							),
					),
				),
			),
		),
	),
	//建宁公主：
	array(
		"img"=>SITE_ROOT."conf/res/gongzhu.jpg",//人物图片 
		"time"=>array(//具体时代
			array(
				"name"=>"",//时代名称
				"people"=>array(//人物配置 
					array(
						"name"=>"建宁公主",//人物名称
						"event"=>array(//特定人物事件
							"和@{username}比体重说：每一次量体重，轻了就对自己说：瘦了。重了就对自己说：胸部大了...",
							"正向@{username}发牢骚：我一不高兴就喜欢吃东西，一吃东西就发胖，一发胖我就很不高兴...",
							),
					),
				),
			),
		),
	),
	//李清照：
	array(
		"img"=>SITE_ROOT."conf/res/meinvv6.gif",//人物图片 
		"time"=>array(//具体时代
			array(
				"name"=>"",//时代名称
				"people"=>array(//人物配置 
					array(
						"name"=>"李清照",//人物名称
						"event"=>array(//特定人物事件
							"和@{username}比体重说：每一次量体重，轻了就对自己说：瘦了。重了就对自己说：胸部大了...",
							"正向@{username}发牢骚：我一不高兴就喜欢吃东西，一吃东西就发胖，一发胖我就很不高兴...",
							),
					),
				),
			),
		),
	),
	//李寻欢：
	array(
		"img"=>SITE_ROOT."conf/res/gongzi.jpg",//人物图片 
		"time"=>array(//具体时代
			array(
				"name"=>"",//时代名称
				"people"=>array(//人物配置 
					array(
						"name"=>"李寻欢",//人物名称
						"event"=>array(//特定人物事件
							),
					),
				),
			),
		),
	),
	//林黛玉、秦可卿：
	array(
		"img"=>SITE_ROOT."conf/res/daiyu.jpg",//人物图片 
		"time"=>array(//具体时代
			array(
				"name"=>"",//时代名称
				"people"=>array(//人物配置 
					array(
						"name"=>"林黛玉",//人物名称
						"event"=>array(//特定人物事件
							"和@{username}比体重说：每一次量体重，轻了就对自己说：瘦了。重了就对自己说：胸部大了...",
							"正向@{username}发牢骚：我一不高兴就喜欢吃东西，一吃东西就发胖，一发胖我就很不高兴...",
							),
					),
					array(
						"name"=>"秦可卿",//人物名称
						"event"=>array(//特定人物事件
							),
					),
				),
			),
		),
	),
	//林仙儿：
	array(
		"img"=>SITE_ROOT."conf/res/zhuwu.jpg",//人物图片 
		"time"=>array(//具体时代
			array(
				"name"=>"",//时代名称
				"people"=>array(//人物配置 
					array(
						"name"=>"林仙儿",//人物名称
						"event"=>array(//特定人物事件
							"和@{username}比体重说：每一次量体重，轻了就对自己说：瘦了。重了就对自己说：胸部大了...",
							"正向@{username}发牢骚：我一不高兴就喜欢吃东西，一吃东西就发胖，一发胖我就很不高兴...",
							),
					),
				),
			),
		),
	),
	//令狐冲、金蛇郎君、谢晓峰：
	array(
		"img"=>SITE_ROOT."conf/res/xiake.jpg",//人物图片 
		"time"=>array(//具体时代
			array(
				"name"=>"",//时代名称
				"people"=>array(//人物配置 
					array(
						"name"=>"令狐冲",//人物名称
						"event"=>array(//特定人物事件
							),
					),
					array(
						"name"=>"金蛇郎君",//人物名称
						"event"=>array(//特定人物事件
							),
					),
					array(
						"name"=>"谢晓峰",//人物名称
						"event"=>array(//特定人物事件
							),
					),
				),
			),
		),
	),
	//陆小凤：
	array(
		"img"=>SITE_ROOT."conf/res/pic1.gif",//人物图片 
		"time"=>array(//具体时代
			array(
				"name"=>"",//时代名称
				"people"=>array(//人物配置 
					array(
						"name"=>"陆小凤",//人物名称
						"event"=>array(//特定人物事件
							"和@{username}比体重说：每一次量体重，轻了就对自己说：瘦了。重了就对自己说：胸部大了...",
							"正向@{username}发牢骚：我一不高兴就喜欢吃东西，一吃东西就发胖，一发胖我就很不高兴...",
							),
					),
				),
			),
		),
	),
	//木婉清：
	array(
		"img"=>SITE_ROOT."conf/res/weiqu.jpg",//人物图片 
		"time"=>array(//具体时代
			array(
				"name"=>"",//时代名称
				"people"=>array(//人物配置 
					array(
						"name"=>"木婉清",//人物名称
						"event"=>array(//特定人物事件
							"和@{username}比体重说：每一次量体重，轻了就对自己说：瘦了。重了就对自己说：胸部大了...",
							"正向@{username}发牢骚：我一不高兴就喜欢吃东西，一吃东西就发胖，一发胖我就很不高兴...",
							),
					),
				),
			),
		),
	),
	//沈浪：
	array(
		"img"=>SITE_ROOT."conf/res/mingyi.jpg",//人物图片 
		"time"=>array(//具体时代
			array(
				"name"=>"",//时代名称
				"people"=>array(//人物配置 
					array(
						"name"=>"沈浪",//人物名称
						"event"=>array(//特定人物事件
							),
					),
				),
			),
		),
	),
	//史湘云、薛宝钗：
	array(
		"img"=>SITE_ROOT."conf/res/baocai.jpg",//人物图片 
		"time"=>array(//具体时代
			array(
				"name"=>"",//时代名称
				"people"=>array(//人物配置 
					array(
						"name"=>"史湘云",//人物名称
						"event"=>array(//特定人物事件
							"和@{username}比体重说：每一次量体重，轻了就对自己说：瘦了。重了就对自己说：胸部大了...",
							"正向@{username}发牢骚：我一不高兴就喜欢吃东西，一吃东西就发胖，一发胖我就很不高兴...",
							),
					),
					array(
						"name"=>"薛宝钗",//人物名称
						"event"=>array(//特定人物事件
							"和@{username}比体重说：每一次量体重，轻了就对自己说：瘦了。重了就对自己说：胸部大了...",
							"正向@{username}发牢骚：我一不高兴就喜欢吃东西，一吃东西就发胖，一发胖我就很不高兴...",
							),
					),
				),
			),
		),
	),
	//鉴真：
	array(
		"img"=>SITE_ROOT."conf/res/img1.jpg",//人物图片 
		"time"=>array(//具体时代
			array(
				"name"=>"",//时代名称
				"people"=>array(//人物配置 
					array(
						"name"=>"鉴真和尚",//人物名称
						"event"=>array(//特定人物事件
							),
					),
				),
			),
		),
	),
	//王熙凤：
	array(
		"img"=>SITE_ROOT."conf/res/wangxifeng.jpg",//人物图片 
		"time"=>array(//具体时代
			array(
				"name"=>"",//时代名称
				"people"=>array(//人物配置 
					array(
						"name"=>"王熙凤",//人物名称
						"event"=>array(//特定人物事件
							"和@{username}比体重说：每一次量体重，轻了就对自己说：瘦了。重了就对自己说：胸部大了...",
							"正向@{username}发牢骚：我一不高兴就喜欢吃东西，一吃东西就发胖，一发胖我就很不高兴...",
							),
					),
				),
			),
		),
	),
	//王语嫣、林诗音：
	array(
		"img"=>SITE_ROOT."conf/res/meinv4.gif",//人物图片 
		"time"=>array(//具体时代
			array(
				"name"=>"",//时代名称
				"people"=>array(//人物配置 
					array(
						"name"=>"王语嫣",//人物名称
						"event"=>array(//特定人物事件
							"和@{username}比体重说：每一次量体重，轻了就对自己说：瘦了。重了就对自己说：胸部大了...",
							"正向@{username}发牢骚：我一不高兴就喜欢吃东西，一吃东西就发胖，一发胖我就很不高兴...",
							),
					),
					array(
						"name"=>"林诗音",//人物名称
						"event"=>array(//特定人物事件
							"和@{username}比体重说：每一次量体重，轻了就对自己说：瘦了。重了就对自己说：胸部大了...",
							"正向@{username}发牢骚：我一不高兴就喜欢吃东西，一吃东西就发胖，一发胖我就很不高兴...",
							),
					),
				),
			),
		),
	),
	//文成公主：
	array(
		"img"=>SITE_ROOT."conf/res/meinv3.gif",//人物图片 
		"time"=>array(//具体时代
			array(
				"name"=>"",//时代名称
				"people"=>array(//人物配置 
					array(
						"name"=>"文成公主",//人物名称
						"event"=>array(//特定人物事件
							"和@{username}比体重说：每一次量体重，轻了就对自己说：瘦了。重了就对自己说：胸部大了...",
							"正向@{username}发牢骚：我一不高兴就喜欢吃东西，一吃东西就发胖，一发胖我就很不高兴...",
							),
					),
				),
			),
		),
	),
	//文天祥：
	array(
		"img"=>SITE_ROOT."conf/res/zhuanyuan.gif",//人物图片 
		"time"=>array(//具体时代
			array(
				"name"=>"",//时代名称
				"people"=>array(//人物配置 
					array(
						"name"=>"文天祥",//人物名称
						"event"=>array(//特定人物事件
							),
					),
				),
			),
		),
	),
	//西门吹雪、叶孤城：
	array(
		"img"=>SITE_ROOT."conf/res/jianke.jpg",//人物图片 
		"time"=>array(//具体时代
			array(
				"name"=>"",//时代名称
				"people"=>array(//人物配置 
					array(
						"name"=>"西门吹雪",//人物名称
						"event"=>array(//特定人物事件
							),
					),
					array(
						"name"=>"叶孤城",//人物名称
						"event"=>array(//特定人物事件
							),
					),
				),
			),
		),
	),
	//小鱼儿、萧十一郎：
	array(
		"img"=>SITE_ROOT."conf/res/jinyiwei.gif",//人物图片 
		"time"=>array(//具体时代
			array(
				"name"=>"",//时代名称
				"people"=>array(//人物配置 
					array(
						"name"=>"小鱼儿",//人物名称
						"event"=>array(//特定人物事件
							),
					),
					array(
						"name"=>"萧十一郎",//人物名称
						"event"=>array(//特定人物事件
							),
					),
				),
			),
		),
	),
	//愚公：
	array(
		"img"=>SITE_ROOT."conf/res/yugong.gif",//人物图片 
		"time"=>array(//具体时代
			array(
				"name"=>"",//时代名称
				"people"=>array(//人物配置 
					array(
						"name"=>"愚公",//人物名称
						"event"=>array(//特定人物事件
							),
					),
				),
			),
		),
	),
	//虞姬：
	array(
		"img"=>SITE_ROOT."conf/res/meinv1.gif",//人物图片 
		"time"=>array(//具体时代
			array(
				"name"=>"",//时代名称
				"people"=>array(//人物配置 
					array(
						"name"=>"虞姬",//人物名称
						"event"=>array(//特定人物事件
							),
					),
				),
			),
		),
	),
	//展昭：
	array(
		"img"=>SITE_ROOT."conf/res/jinyiwei2.gif",//人物图片 
		"time"=>array(//具体时代
			array(
				"name"=>"",//时代名称
				"people"=>array(//人物配置 
					array(
						"name"=>"展昭",//人物名称
						"event"=>array(//特定人物事件
							),
					),
				),
			),
		),
	),
	//卓别林：
	array(
		"img"=>SITE_ROOT."conf/res/jack.jpg",//人物图片 
		"time"=>array(//具体时代
			array(
				"name"=>"",//时代名称
				"people"=>array(//人物配置 
					array(
						"name"=>"卓别林",//人物名称
						"event"=>array(//特定人物事件
							),
					),
				),
			),
		),
	),
	//白飞飞：
	array(
		"img"=>SITE_ROOT."conf/res/meimei.jpg",//人物图片 
		"time"=>array(//具体时代
			array(
				"name"=>"",//时代名称
				"people"=>array(//人物配置 
					array(
						"name"=>"白飞飞",//人物名称
						"event"=>array(//特定人物事件
							"和@{username}比体重说：每一次量体重，轻了就对自己说：瘦了。重了就对自己说：胸部大了...",
							"正向@{username}发牢骚：我一不高兴就喜欢吃东西，一吃东西就发胖，一发胖我就很不高兴...",	
						),
					),
				),
			),
		),
	),
	//八戒：
	array(
		"img"=>SITE_ROOT."conf/res/bajie.jpg",//人物图片 
		"time"=>array(//具体时代
			array(
				"name"=>"",//时代名称
				"people"=>array(//人物配置 
					array(
						"name"=>"猪八戒",//人物名称
						"event"=>array(//特定人物事件
						"和@{username}说:猪有猪的思想，人有人的思想。如果猪有人的思想，那它就是我-八戒！",
						"对@{username}说：按照我的审美观，你基本算得上是个帅哥。",
						"对@{username}说：如果猪都像我一样会飞，那谁还买飞机？骑着猪上天不就行了。",
						),
					),
				),
			),
		),
	),
	//兰陵王：
	array(
		"img"=>SITE_ROOT."conf/res/lanlingwang.jpg",//人物图片 
		"time"=>array(//具体时代
			array(
				"name"=>"",//时代名称
				"people"=>array(//人物配置 
					array(
						"name"=>"兰陵王",//人物名称
						"event"=>array(//特定人物事件
						),
					),
				),
			),
		),
	),
	//李师师：
	array(
		"img"=>SITE_ROOT."conf/res/lishishi.jpg",//人物图片 
		"time"=>array(//具体时代
			array(
				"name"=>"",//时代名称
				"people"=>array(//人物配置 
					array(
						"name"=>"李师师",//人物名称
						"event"=>array(//特定人物事件
						),
					),
				),
			),
		),
	),
	//李寻欢：
	array(
		"img"=>SITE_ROOT."conf/res/lixunhuan.jpg",//人物图片 
		"time"=>array(//具体时代
			array(
				"name"=>"",//时代名称
				"people"=>array(//人物配置 
					array(
						"name"=>"李寻欢",//人物名称
						"event"=>array(//特定人物事件
						),
					),
				),
			),
		),
	),
	//莫小贝：
	array(
		"img"=>SITE_ROOT."conf/res/moxianbei.jpg",//人物图片 
		"time"=>array(//具体时代
			array(
				"name"=>"",//时代名称
				"people"=>array(//人物配置 
					array(
						"name"=>"莫小贝",//人物名称
						"event"=>array(//特定人物事件
						),
					),
				),
			),
		),
	),
	//哪吒：
	array(
		"img"=>SITE_ROOT."conf/res/nezha.jpg",//人物图片 
		"time"=>array(//具体时代
			array(
				"name"=>"",//时代名称
				"people"=>array(//人物配置 
					array(
						"name"=>"哪吒",//人物名称
						"event"=>array(//特定人物事件
						),
					),
				),
			),
		),
	),
	//宁采臣：
	array(
		"img"=>SITE_ROOT."conf/res/ningcaicheng.jpg",//人物图片 
		"time"=>array(//具体时代
			array(
				"name"=>"",//时代名称
				"people"=>array(//人物配置 
					array(
						"name"=>"宁采臣",//人物名称
						"event"=>array(//特定人物事件
						),
					),
				),
			),
		),
	),
	//秦始皇：
	array(
		"img"=>SITE_ROOT."conf/res/qinshihuang.jpg",//人物图片 
		"time"=>array(//具体时代
			array(
				"name"=>"",//时代名称
				"people"=>array(//人物配置 
					array(
						"name"=>"秦始皇",//人物名称
						"event"=>array(//特定人物事件
						),
					),
				),
			),
		),
	),
	//三圣母：
	array(
		"img"=>SITE_ROOT."conf/res/sanshengmu.jpg",//人物图片 
		"time"=>array(//具体时代
			array(
				"name"=>"",//时代名称
				"people"=>array(//人物配置 
					array(
						"name"=>"三圣母",//人物名称
						"event"=>array(//特定人物事件
						),
					),
				),
			),
		),
	),
	//卫子夫：
	array(
		"img"=>SITE_ROOT."conf/res/weizifu.jpg",//人物图片 
		"time"=>array(//具体时代
			array(
				"name"=>"",//时代名称
				"people"=>array(//人物配置 
					array(
						"name"=>"卫子夫",//人物名称
						"event"=>array(//特定人物事件
						),
					),
				),
			),
		),
	),
	//香妃：
	array(
		"img"=>SITE_ROOT."conf/res/xiangfei.jpg",//人物图片 
		"time"=>array(//具体时代
			array(
				"name"=>"",//时代名称
				"people"=>array(//人物配置 
					array(
						"name"=>"香妃",//人物名称
						"event"=>array(//特定人物事件
						),
					),
				),
			),
		),
	),
	//小燕子：
	array(
		"img"=>SITE_ROOT."conf/res/xiaoyanzi.jpg",//人物图片 
		"time"=>array(//具体时代
			array(
				"name"=>"",//时代名称
				"people"=>array(//人物配置 
					array(
						"name"=>"小燕子",//人物名称
						"event"=>array(//特定人物事件
						),
					),
				),
			),
		),
	),
	//邢捕头：
	array(
		"img"=>SITE_ROOT."conf/res/xinbutou.jpg",//人物图片 
		"time"=>array(//具体时代
			array(
				"name"=>"",//时代名称
				"people"=>array(//人物配置 
					array(
						"name"=>"邢捕头",//人物名称
						"event"=>array(//特定人物事件
						),
					),
				),
			),
		),
	),
	//叶赫那拉：
	array(
		"img"=>SITE_ROOT."conf/res/yehelala.jpg",//人物图片 
		"time"=>array(//具体时代
			array(
				"name"=>"",//时代名称
				"people"=>array(//人物配置 
					array(
						"name"=>"叶赫那拉",//人物名称
						"event"=>array(//特定人物事件
						),
					),
				),
			),
		),
	),
);

//公共事件配置
$common_event_cfg = array(
	"穿了一件印着@{username}卸妆后素颜照的白T恤去公司参加最丑衣服竞赛，结果得了第一！",
	"和@{username}蹲在街上抓拍美女，准备参加一年一度“寻找潘金莲”武大郎烧饼摄影大赛",
	"和@{username}在人山人海的苹果专卖店抢购才上市的ipad2,被挤成了矮冬瓜，滚了出来！",
	"和@{username}在看《中华上下五百年》，发现自己比书里写的帅，不由的跳起了杰克逊的舞蹈！",
	"和@{username}一起躺在草地上晒太阳，抠着鼻屎看着浮云，感叹到：这才是人生啊！！！！",
	"对@{username}说：哎，眼看我快奔三了，可是我还没二够",
	"和@{username}正参加二狗村村委会换届选举，历来村干部都以一无是处当选。因优点太多，没被选上",
	"正在参加高考。拿到试卷透心凉,一紧张．词汇忘．似曾相识、解释却不详。我了个去，今年又上不了榜",
	"在@{username}前炫耀：我会盲打，我打字从来不看屏幕，只看键盘！后来才知道盲打是不看键盘只看屏幕的……",
	"对@{username}说：一想到2012就要来了，一想到我还欠银行的钱，我连做梦都能笑醒！",
	"正在嚎啕大哭，因为准备的毕业论文是《论本拉登逍遥法外与美国社会市场体制的必然联系》...",
	"对@{username}说：你长的真是酷毙了？长相太残酷应该拉出去毙了！",
	"和@{username}一起聊天，“特别能吃苦”这5个字，我想了想，我做到了前四个...",
	"刚作了一首诗，读给@{username}听：远看一座庙，近看咱母校，三百多尼姑，一万多老道。",
	"上班在车上睡着了。突然手机响起：启奏皇上，有一刁民求见，是接了还是斩了？顿时，车上鸦雀无声...",
	"问@{username}：微博跟微软是什么关系？ 答曰：时间关系！内涵啊！！！当时就羞涩了。",
	"对@{username}说：聪明的男人不会吵架，因为他们知道，男人是吵不过女人的...",
	"又考试！老师说：请把和考试无关的东西放到讲台上。我很想把自己放上去！",
	"在教@{username}说绕口令：老龙恼怒闹老农，老农恼怒闹老龙。农怒龙恼农更怒，龙恼农怒龙怕农 ",
	"看着@{username}的新发型说：你这发型性价比很高！才花一百五，却剪了个二百五的头。",
	"正和@{username}玩捉迷藏，等@{username}一藏好，就跑回家游戏去了！",
	"和@{username}一起参加了一个比赛---放鸽子大赛！结果比赛时就这两2去了...",
	"对@{username}说：虽然洗面奶上写着清洁美白，但你也不能把它当牙膏用啊！",
	"对@{username}一笑：娶个兵作老婆，那就不会赔了夫人又折兵。",
	"对@{username}说：谈钱多伤感情，咱还是谈谈支票吧。",
	"对@{username}说：看在你没头发的面子上，买梳子给你打对折之后再打对折。",
	"对@{username}说：哇，你的样子真的好棒，棒的跟棒槌一个样。",
	"对@{username}说：俗话说情人眼里出西施，你站在我面前，我看到的只有眼屎。",
	"对@{username}说:装什么装，人又不聪明，还敢学人家秃顶。",
	"对@{username}说:你把郁闷俩字都写脸上了，不识字的还真看不出来。",
	"和@{username}下棋，说:其实我并不想挂帅，谁叫我下象棋时走的是红棋呢。",
	"看着@{username}说：其实你的丑是特别的，就是特别的丑。",
	"对@{username}说：其实你长得还可以，就是看起来象素比较低。",
	"对@{username}说:睡眠是一门艺术，谁也无法阻挡我追求艺术的脚步。",
	"对@{username}说:我知道你不是随便的人，因为你随便起来不是人。",
	"对@{username}说:佛祖会原谅你犯的错，而我的任务就是送你上西天。",
	"对@{username}说:瞧瞧你自个，左脑袋面粉，右脑袋水，一想问题就满脑袋糨糊。",
	"对@{username}说：这年头油价越涨越高，揩油的人却越来越多。",
	"对@{username}说：你要知道会烧香的不一定是和尚，也可能是熊猫。",
	"对@{username}说：我悄悄地来，悄悄地走，挥一挥匕首，不留一个活口。",
	"对@{username}说：找对象的时候一定要看仔细，现在不男不女的人太多了。",
	"对@{username}说：您凭什么说我长得随心所欲，看看你，长得那叫为所欲为。",
	"对@{username}说：买了电脑不上宽带，就好比酒肉都准备好了却在吃饭前当了和尚。",
	"对@{username}说：不要在一棵树上吊死，在几棵树上多试试死几次……--死就死得彻底！",
	"对@{username}说：下辈子我还找你，因为除了我，你是最傻的。",
	"对@{username}说：有一个很古老的传说，说是在北邮校园内能看到美女的人会长生不老……",
	"对@{username}说：我想，只要我再稍微具有一些谦虚的品质，我就是个完美的人了。",
	"对@{username}说：你信不信我一巴掌把你拍墙上,抠都抠不下来!",
	"对@{username}说：你就像一只趴在玻璃上的苍蝇，看着前面的光明却找不到出路。",
	"对@{username}说：在烈火中重新站起来的，不一定是涅槃，也可能是尸变。",
	"对@{username}说：看到这么多在新浪转世的朋友，被封了又重开，我由衷的觉得新浪应该改名叫“开封府”。",
	"对@{username}说：众里寻你千百度，蓦然回首，你依旧对我不屑一顾……",
	"对@{username}说：唾沫是用来数钞票的，不是用来讲道理的",
	"和@{username}说：看我有的是背景儿，看你只能是背影儿。",
	"和@{username}说：爱情吧，死活是个死，生活吧，死活都得活，两个一凑合，就会折腾的半死不活。",
	"对@{username}说：名花虽有主,锄头更无情 ,只要锄头挥得好,哪有墙角挖不倒",
	"对@{username}说：欲使人灭亡，必先使其疯狂；欲使人疯狂，必先使其买房。结论：现在不能买房！",
	"对@{username}说：佛祖曰：武功再高`也怕菜刀`;穿的再叼 `一砖撂倒 。",
	"对@{username}说：我不是你想象中的那样完美那样坚强，金钱和美女就足以把我征服！",
	"对@{username}说：孔子曰：打架用砖乎，照脸乎；乎不着再乎，乎着往死里乎；乎死即拉倒；不死者乃英雄也~~",
	"对@{username}说：当时我的结婚钻戒离下水道只有10公分！四分之一炷香之后，我终于决定再买个大钻戒备份！",
	"对@{username}说：不挂科，我所欲也；不学习，亦我所欲也。二者不可兼得，我嘞个去也",
	"对@{username}说：那么高的个子，不做女娲就浪费了，补天都不带踮脚的",
	"对@{username}说：家长会后修改签名了吧：家长会和小三的性质都是一样的，旨在破坏家庭和谐...",
	"对@{username}说：我想有一所房子，面朝大海，春暖花开，4M宽带，能叫外卖，快递直达，不还房贷！",
	"对@{username}说：我想有一个朋友，评评小说，侃侃明星，不愁房贷，能去买菜，可以喝茶，还能恋爱！",
	"对@{username}说：使用龟派气功的最高境界，就是变身为......海绵宝宝！！！",
	"给@{username}讲冷笑话：从前有一只鸟，它飞着飞着就摔死了。为什么呢？ ......因为它的内裤掉了！",
	"给@{username}讲冷笑话：有个人，拿着白色爱疯4去滑雪，然后爱疯掉地上了，然后... 然后就不见了...",
	"对@{username}说：鄙视我的人那么多，你算老几? ",
	"对@{username}说：交给我你就不用放心了，没有错不了的事！ ",
	"对@{username}说：你骄傲的从我身边走过，却没有发先你那红色的线裤漏在外面...",
	"对@{username}说：只有娶不到老婆的男人，没有嫁不出去的女人。",
);

