//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by BTSMonitor.rc
//
#define IDI_WARNING_VIEW_HC             5
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDD_RUNTIME_WARNING             101
#define IDS_FIND_CAMERA                 101
#define IDS_RIBBON_FIND_CAMERA          102
#define IDS_STRING103                   103
#define IDS_WARNING                     103
#define IDP_SOCKETS_INIT_FAILED         104
#define IDB_WRITESMALL                  110
#define IDB_WRITELARGE                  111
#define IDB_MAIN                        112
#define IDB_BUTTONS                     113
#define IDB_FILELARGE                   114
#define IDB_FILESMALL                   115
#define IDR_POPUP_EDIT                  119
#define ID_STATUSBAR_PANE1              120
#define ID_STATUSBAR_PANE2              121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define IDR_BTSMonitorTYPE              130
#define ID_WINDOW_MANAGER               131
#define IDS_WINDOWS_MANAGER             132
#define ID_VIEW_FILEVIEW                133
#define ID_VIEW_CLASSVIEW               134
#define ID_PROPERTIES                   135
#define ID_OPEN                         136
#define ID_OPEN_WITH                    137
#define ID_DUMMY_COMPILE                138
#define ID_CLASS_ADD_MEMBER_FUNCTION    139
#define ID_CLASS_ADD_MEMBER_VARIABLE    140
#define ID_CLASS_DEFINITION             141
#define ID_CLASS_PROPERTIES             142
#define ID_NEW_FOLDER                   143
#define ID_SORT_MENU                    144
#define ID_SORTING_GROUPBYTYPE          145
#define ID_SORTING_SORTALPHABETIC       146
#define ID_SORTING_SORTBYTYPE           147
#define ID_SORTING_SORTBYACCESS         148
#define IDR_PASTE_MENU                  151
#define IDR_WINDOWS_MENU                152
#define IDS_FILE_VIEW                   155
#define IDS_CLASS_VIEW                  156
#define IDI_FILE_VIEW                   161
#define IDI_FILE_VIEW_HC                162
#define IDI_CLASS_VIEW                  163
#define IDI_CLASS_VIEW_HC               164
#define IDR_EXPLORER                    169
#define IDB_EXPLORER_24                 170
#define IDR_SORT                        171
#define IDB_SORT_24                     172
#define IDR_POPUP_SORT                  173
#define IDR_POPUP_EXPLORER              174
#define IDB_FILE_VIEW                   175
#define IDB_FILE_VIEW_24                176
#define IDB_CLASS_VIEW                  177
#define IDB_CLASS_VIEW_24               178
#define IDR_MENU_IMAGES                 179
#define IDB_MENU_IMAGES_24              180
#define ID_TOOLS_MACRO                  181
#define IDB_CAMERA_VIEW                 181
#define IDB_SYSTEMLARGE                 182
#define IDB_SYSTEMSMALL                 183
#define IDB_MONITOR_LARGE               184
#define IDB_WRITESMALL1                 185
#define IDB_MONITOR_SMALL               185
#define IDR_THEME_MENU                  200
#define ID_SET_STYLE                    201
#define ID_VIEW_APPLOOK_WIN_2000        210
#define ID_VIEW_APPLOOK_OFF_XP          211
#define ID_VIEW_APPLOOK_WIN_XP          212
#define ID_VIEW_APPLOOK_OFF_2003        213
#define ID_VIEW_APPLOOK_VS_2005         214
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   215
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  216
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 217
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   218
#define IDS_RIBBON_FILE                 260
#define IDS_RIBBON_NEW                  262
#define IDS_RIBBON_OPEN                 263
#define IDS_RIBBON_SAVE                 264
#define IDS_RIBBON_SAVEAS               265
#define IDS_RIBBON_PRINT                266
#define IDS_RIBBON_PRINT_LABEL          267
#define IDS_RIBBON_PRINT_QUICK          268
#define IDS_RIBBON_PRINT_PREVIEW        269
#define IDS_RIBBON_PRINT_SETUP          270
#define IDS_RIBBON_CLOSE                271
#define IDS_RIBBON_RECENT_DOCS          272
#define IDS_RIBBON_EXIT                 273
#define IDS_RIBBON_HOME                 274
#define IDS_RIBBON_CLIPBOARD            275
#define IDS_RIBBON_PASTE                276
#define IDS_RIBBON_CUT                  277
#define IDS_RIBBON_COPY                 278
#define IDS_RIBBON_SELECTALL            279
#define IDS_RIBBON_WINDOW               284
#define IDS_RIBBON_WINDOWS              285
#define IDS_RIBBON_STYLE                286
#define IDS_RIBBON_STYLE_TIP            287
#define IDS_RIBBON_STYLE_DESC           288
#define IDS_RIBBON_STATUSBAR            289
#define IDS_RIBBON_VIEW                 290
#define IDS_EXPLORER                    305
#define IDS_EDIT_MENU                   306
#define ID_VIEW_WARNING                 310
#define ID_VIEW_CAMERA                  311
#define IDI_WARNING_VIEW                312
#define ID_EBOX_FIND                    312
#define ID_BTN_FIND                     313
#define IDD_CRITICAL_WARNING            314
#define IDD_GENERAL_WARNING             315
#define IDD_DLG_FIND                    316
#define IDD_DLG_LOGIN                   317
#define IDI_UNKNOWN                     318
#define IDI_UNACK                       319
#define IDI_ACK                         320
#define IDR_MENU_WARNING                321
#define IDD_POP_VIDEO                   322
#define IDD_WARNING_CONFIG              323
#define IDR_HTML_DLGIMAGE               324
#define IDD_WARNING_MGR                 325
#define IDD_TASK_MGR                    326
#define IDI_ICON_SETTING                327
#define IDI_ICON1                       337
#define IDI_LOGON                       337
#define IDB_BITMAP1                     339
#define IDB_DGM_LOGO                    339
#define IDI_LEVEL_2                     341
#define IDI_LEVEL_1                     342
#define IDI_LEVEL_3                     343
#define IDD_USER_MGR                    343
#define IDI_LEVEL_4                     344
#define IDR_POPMENU_WARNMGR             344
#define IDI_LEVEL_5                     345
#define IDR_POPUP_PLAYVIEW              345
#define IDD_DLG_IMAGE                   346
#define IDC_LST_RUNTIME_WARNING         1000
#define IDC_LIST_GENERAL_WARNING        1000
#define IDC_LIST_CRITICAL_WARNING       1000
#define IDC_FINDSTR                     1001
#define IDC_EDIT_USER                   1002
#define IDC_EDIT_PWD                    1003
#define IDC_EDIT_SERVER                 1004
#define IDC_CHK_MOTION_DETECTION        1005
#define IDC_CHK_IR_DETECTION            1006
#define IDC_CHK_VIDEO_COVER             1007
#define IDC_CHK_VIDEO_LOSS              1008
#define IDC_CHK_NO_WARNING              1009
#define IDC_CMB_POPWND_COUNT            1010
#define IDC_WARNING_WAVE                1011
#define IDC_WAVE_BROWSE                 1012
#define IDC_CMB_PICTURE_WINDOW          1013
#define IDC_EDIT_DEVICE_FIND            1013
#define IDC_CMB_PICTURE_PLAY_INTERVAL   1014
#define IDC_FILTER_TYPE                 1014
#define IDC_BTN_WARN_MGR_DEVICE_FIND    1015
#define IDC_TREE_WARN_MGR_DEVICE        1016
#define IDC_COMBO2                      1017
#define IDC_CBO_WARN_TYPE               1017
#define IDC_DATETIMEPICKER1             1018
#define IDC_DATE_BEGIN                  1018
#define IDC_DATETIMEPICKER2             1019
#define IDC_DATE_END                    1019
#define IDC_CBO_START_HOUR              1020
#define IDC_CBO_END_HOUR                1021
#define IDC_CBO_START_MINUTE            1022
#define IDC_CBO_START_SECOND            1023
#define IDC_CBO_END_MINUTE              1024
#define IDC_CBO_END_SECOND              1025
#define IDC_LIST1                       1026
#define IDC_LST_TARGET_WARNING          1026
#define IDC_BTN_PAUSE                   1027
#define IDC_BTN_STOP                    1028
#define IDC_BTN_PLAY                    1029
#define IDC_BTN_FAST_FORWARD            1030
#define IDC_BTN_RECORD                  1031
#define IDC_CBO_WARN_ACK_TYPE           1031
#define IDC_BTN_SNAP                    1032
#define IDC_BTN_GOTO_BEGIN              1033
#define IDC_BTN_GOTO_END                1034
#define IDC_BTN_GOTO_END2               1035
#define IDC_CHK_SOUND                   1036
#define IDC_SLD_SOUND_CTRL              1037
#define IDC_EDIT_TASK_NAME              1038
#define IDC_CBO_TARGET_WINDOW           1039
#define IDC_BTN_TASK_ADD                1040
#define IDC_LST_TASK                    1041
#define IDC_DATETIME_START              1042
#define IDC_DATETIME_END                1043
#define IDC_EDIT_DEVICEID               1044
#define IDC_CBO_DEVICE_ID               1044
#define IDC_OGON_PIC                    1045
#define IDC_DGM_LOGO                    1046
#define IDC_EDT_USER                    1048
#define IDC_EDT_PASSWORD                1049
#define IDC_EDT_NEW_PW2                 1050
#define IDC_EDT_NEW_PW                  1051
#define IDC_BTN_MOD                     1053
#define IDC_SAVE_PASSED_VIDEO           1055
#define IDC_FIND_TARGET_WARNING         1060
#define IDC_WINDOW_VEDIO                1061
#define IDC_CBO_USER                    1063
#define IDC_CBO_SERVER                  1064
#define IDC_BTN_DELETE_TASK             1064
#define IDC_CBO_PORT                    1065
#define IDC_CBO_CHANNEL                 1065
#define IDC_PAUSE_ALARM                 1067
#define IDC_EDIT1                       1068
#define IDC_TIMEOUT                     1068
#define ID_WRITE_PASTEASHYPERLINK       32770
#define ID_FIND_CAMERA                  32771
#define ID_VV1                          32781
#define ID_VV4                          32782
#define ID_VV6                          32783
#define ID_VV8                          32784
#define ID_VV9                          32785
#define ID_VV16                         32786
#define ID_VV25                         32787
#define ID_WARNING_ACK                  32788
#define ID_WARNING_SCROOLING_ON         32791
#define ID_WARNING_SCROOLING_OFF        32792
#define ID_32793                        32793
#define ID_32794                        32794
#define ID_32795                        32795
#define ID_32796                        32796
#define ID_SYSTEM_CONFIG                32797
#define ID_WARNING_MGR                  32798
#define ID_TASK_MGR                     32799
#define ID_USER_MGR                     32800
#define ID_WARNINGMGR_32801             32801
#define ID_WARNINGMGR_32802             32802
#define ID_WARNINGMGR_EXPORT            32803
#define ID_WARNINGMGR_SAVEAS            32804
#define ID_PLAYVIEW_32805               32805
#define ID_PLAYVIEW_CLOSE               32806
#define ID_PLAYVIEW_32807               32807
#define ID_PLAYVIEW_FULLSCREEN          32808

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        348
#define _APS_NEXT_COMMAND_VALUE         32809
#define _APS_NEXT_CONTROL_VALUE         1069
#define _APS_NEXT_SYMED_VALUE           325
#endif
#endif
