#ifndef USERDEFMSG_H_
#define USERDEFMSG_H_

#define MSG_LOGINOK			WM_USER+200
#define MSG_LOGINFAIL		WM_USER+201
#define MSG_GETBTSLIST		WM_USER+202
#define MSG_GETBTSLISTOK	WM_USER+203
#define MSG_GETBTSLISTFAIL	WM_USER+204

#endif