//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by player264demo.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_PLAYER264DEMO_DIALOG        102
#define IDR_MAINFRAME                   128
#define IDR_MENU1                       129
#define IDD_DIALOG1                     130
#define IDD_DIALOG_LOCATE               130
#define IDB_BITMAP                      131
#define IDD_DIALOG_MultiDisplay         132
#define IDD_DIALOG_SYS_INFO             133
#define IDD_DIALOG_CUTFILE              134
#define IDB_OVERLAY                     135
#define IDD_DIALOG_SEARCH               136
#define IDD_DIALOG_WATERMARK            141
#define IDD_DIALOG_MEDIAINFO            142
#define IDD_DIALOG_AVICONV              143
#define IDB_BITMAP_PLAY                 144
#define IDB_BITMAP_FAST                 145
#define IDB_BITMAP_PAUSE                146
#define IDB_BITMAP_CAMERA               148
#define IDB_BITMAP_FULLSCREEN           149
#define IDB_BITMAP_SEEKTOEND            150
#define IDB_BITMAP_SEEKTOSTART          151
#define IDB_BITMAP_SOUND                153
#define IDB_BITMAP_STEPBACKWARD         154
#define IDB_BITMAP_STEPFORWARD          155
#define IDB_BITMAP_STOP                 156
#define IDB_BITMAP_SLOW                 157
#define IDD_DIALOG_COLORSET             158
#define IDB_BITMAP_SETCOLOR             159
#define IDD_DIALOG_SETPATH              160
#define IDD_DIALOG_AUDIOIN              161
#define IDC_SLIDER_PLAY                 1000
#define IDC_BUTTON_PLAY                 1001
#define IDC_BUTTON_PAUSE                1002
#define IDC_BUTTON_FAST                 1003
#define IDC_BUTTON_SLOW                 1004
#define IDC_BUTTON_BACKONE              1005
#define IDC_BUTTON_ONE                  1006
#define IDC_BUTTON_TOBEGIN              1007
#define IDC_BUTTON_TOEND                1008
#define IDC_BUTTON_PICCATCH             1009
#define IDC_BUTTON_STOP                 1010
#define IDC_SLIDERS                     1011
#define IDC_SLIDERC                     1012
#define IDC_SLIDERB                     1013
#define IDC_SLIDERH                     1014
#define IDC_SLIDER_SOUND                1015
#define IDC_STATIC_SHOW                 1016
#define IDC_STATIC_FRAME                1017
#define IDC_STATIC_PLAYSTATE            1017
#define IDC_STATIC_VER                  1018
#define IDC_STATIC_TIME                 1019
#define IDC_STATIC_CURINFO              1019
#define IDC_RADIO_FRAME                 1020
#define IDC_RADIO_TIME                  1021
#define IDC_STATIC_RANGE                1022
#define IDC_EDIT_RANGEVALUE             1023
#define IDC_BUTTON_LOCATE               1024
#define IDC_BUTTON_DISPLAY              1025
#define IDC_EDIT_LEFT                   1026
#define IDC_EDIT_RIGHT                  1027
#define IDC_EDIT_TOP                    1028
#define IDC_EDIT_BOTTOM                 1029
#define IDC_STATIC_PART_DISPLAY         1030
#define IDC_STATIC_INFO                 1031
#define IDC_BUTTON_REFRESH              1032
#define IDC_OK                          1033
#define IDC_CHECK_SOUND                 1035
#define IDC_RADIO_BYFRAME               1036
#define IDC_EDIT_START_POSITION         1038
#define IDC_EDIT_END_POSITION           1039
#define IDC_BUTTON_SAVEFILE             1040
#define IDC_EDIT_startposition          1041
#define IDC_EDIT_endposition            1042
#define IDC_BUTTON_GETERROR             1044
#define IDC_FULLSCREEN                  1045
#define IDC_STATICB                     1046
#define IDC_BUTTON_SETCOLOR             1046
#define IDC_STATICD                     1047
#define IDC_STATICL                     1048
#define IDC_STATICS                     1049
#define IDC_GROUPBOX1                   1050
#define IDC_GROUPBOX2                   1051
#define IDC_STATIC1                     1052
#define IDC_STATIC2                     1053
#define IDC_EDIT_BUTTOM                 1059
#define IDC_EDIT_VALUE                  1060
#define IDC_RADIO_SEARCH_TYPE           1064
#define IDC_RADIO2                      1065
#define IDC_BUTTON_PREMDFRAME           1066
#define IDC_EDIT_BEGIN_VALUE            1067
#define IDC_EDIT_END_VALUE              1068
#define IDC_BUTTON_NEXTMDFRAME          1069
#define IDC_SPIN1                       1072
#define IDC_EDIT_CHECKFILEPATH          1076
#define IDC_BUTTON_CHECKFILE            1077
#define IDC_EDIT_WATREMARK              1078
#define IDC_LIST_WATERINFO              1079
#define IDC_PROGRESS_CHECK              1080
#define IDC_BUTTON_CHECK                1081
#define IDC_EDIT_SRCFILE                1082
#define IDC_BUTTON_SRCFILE              1083
#define IDC_EDIT_TARGFILE               1084
#define IDC_BUTTON_TARGFILE             1085
#define IDC_BUTTON_CONVERT              1086
#define IDC_PROGRESS_CONVERT            1087
#define IDC_BUTTON_SOUND                1089
#define IDC_STATIC_STATEINFO            1090
#define IDC_EDIT_PICPATH                1092
#define IDC_BUTTON_PATHSET              1093
#define IDC_EDIT_SOUNDFILE              1094
#define IDC_BUTTON_SOUNDFILE            1095
#define IDC_BUTTON_RECORD               1099
#define IDC_COMBO_BIT                   1100
#define IDC_COMBO_SAMPLES               1101
#define ID_EXIT                         32771
#define ID_REPEAT                       32772
#define ID_LOCATE                       32773
#define ID_ABOUT                        32774
#define ID_RESETBUF                     32775
#define ID_STOREYUVDATA                 32776
#define ID_PART_DISPLAY                 32779
#define IDC_SYSINFO                     32780
#define IDC_CUTFILE                     32781
#define ID_AUDIO_CALLBACK               32786
#define ID_OPEN_LAST_FILE               32787
#define ID_DEC_AUDIO                    32789
#define ID_DEC_VIDEO                    32790
#define ID_DEC_COMPLEX                  32791
#define ID_DEC_NONE                     32792
#define ID_SEARCH                       32793
#define ID_MENUITEM32794                32794
#define ID_MENUITEM32795                32795
#define ID_MENUITEM_Chinese             32796
#define ID_MENUITEM_English             32797
#define IDC_VERTICALSYNC                32799
#define ID_FILEMODE_FILE                32800
#define ID_FILEMODE_STREAM              32801
#define ID_PIC_BMP                      32802
#define ID_PIC_JPG                      32803
#define ID_OPT_AVICONVER                32804
#define ID_OPT_WATERMARK                32805
#define ID_INFO_MEDIA                   32806
#define ID_SET_PICPATH                  32808
#define ID_MENUITEM_AUDIOIN             32809

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        162
#define _APS_NEXT_COMMAND_VALUE         32810
#define _APS_NEXT_CONTROL_VALUE         1102
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
