CREATE TABLE ms_sugar_question(
usr_id INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
question text,
order_by integer(11),
active integer(11) default 1 -- 1 is active. 0 is non-active
);


CREATE TABLE ms_sugar_answer(
usr_id INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
description text,
min_yes integer(11),
max_yes integer(11),
user_count integer(11),
active integer(11) default 1 -- 1 is active. 0 is non-active
);

CREATE TABLE ms_sugar_user(
fb_uid integer(11) UNSIGNED NOT NULL PRIMARY KEY,
sugar_category integer(11),
quiz_answer varchar(255),
joined integer(1) default 0, -- 1 is joined. 0 isn't join

--name varchar(64),
gender integer(1), 
location integer(10), 
seeking integer(1), 
--email varchar(128), 
--im varchar(64), 
photo varchar(255), 
description text,

create_date datetime,
join_date timestamp
);

CREATE TABLE ms_sugar_featured(
fb_uid integer(11) UNSIGNED NOT NULL PRIMARY KEY,
create_date timestamp default now()
);

CREATE TABLE country_list(
cid integer(11) UNSIGNED NOT NULL PRIMARY KEY,
name varchar(255)
);


insert ms_sugar_question(question, order_by)
values ('Do you take pre-Marital sex easy?', 1),
('Do you take extra-Marital sex easy?', 2),
('Is it human instinct to be attracted to beauty as it is to be attracted to wealth and power?', 3),
('Do you love to treated like a king or queen?', 4),
('Are you generous to support or care?', 5),
('Is it human nature for people to want younger and more attractive partners?', 6),
('Is it natural for younger men & women to seek out more experienced, sophisticated partners, specifically those who have the means of providing them with comforts and luxuries?', 7),
('Are you mature and rich or young but in financial difficulty?', 8),
('Are you interested in a discreet and mutually beneficial relationship?', 9),
('Are you want good living and finer things in life and also share with others?', 10);


insert ms_sugar_answer(description, min_yes, max_yes, user_count)
values ('like Sugardaddy Lifestyle.', 10, 100, 0),
 ('are absolutely interested in Sugardaddy Lifestyle.', 8, 9, 0),
 ('are probably interested in Sugardaddy Lifestyle.', 5, 7, 0),
 ('are probably not interested in Sugardaddy Lifestyle.', 3, 4, 0),
('are not interested in Sugardaddy Lifestyle.', 1, 2, 0),
('hate Sugardaddy Lifestyle.', -1, 0, 0);


insert country_list(cid, name)
values 
(0, 'United States'),
(31, 'Canada'),
(180, 'United Kingdom'),
(1, 'Afghanistan'),
(2, 'Albania'),
(3, 'Algeria'),
(4, 'Andorra'),
(5, 'Angola'),
(201, 'Anguilla'),
(6, 'Antigua & Barbuda'),
(7, 'Argentina'),
(8, 'Armenia'),
(196, 'Aruba'),
(9, 'Australia'),
(10, 'Austria'),
(11, 'Azerbaijan'),
(12, 'Bahamas'),
(13, 'Bahrain'),
(14, 'Bangladesh'),
(15, 'Barbados'),
(17, 'Belgium'),
(18, 'Belize'),
(19, 'Benin'),
(197, 'Bermuda'),
(20, 'Bhutan'),
(21, 'Bolivia'),
(22, 'Bosnia and Herzegovina'),
(23, 'Botswana'),
(24, 'Brazil'),
(203, 'British Indian Ocean Territory'),
(25, 'Brunei Darussalam'),
(26, 'Bulgaria'),
(27, 'Burkina Faso'),
(28, 'Burundi'),
(29, 'Cambodia'),
(30, 'Cameroon'),
(32, 'Cape Verde'),
(204, 'Cayman Islands'),
(33, 'Central African Republic'),
(34, 'Chad'),
(35, 'Chile'),
(36, 'China'),
(37, 'Colombia'),
(38, 'Comoros'),
(205, 'Cook Islands'),
(41, 'Costa Rica'),
(43, 'Croatia'),
(45, 'Cyprus'),
(46, 'Czech Republic'),
(47, 'Denmark'),
(48, 'Djibouti'),
(49, 'Dominica'),
(50, 'Dominican Republic'),
(51, 'Ecuador'),
(52, 'Egypt'),
(53, 'El Salvador'),
(54, 'Equatorial Guinea'),
(55, 'Eritrea'),
(56, 'Estonia'),
(57, 'Ethiopia'),
(236, 'Europe'),
(206, 'Falkland Islands'),
(207, 'Faroe Islands'),
(208, 'Federated States of Micronesia'),
(58, 'Fiji'),
(59, 'Finland'),
(60, 'France'),
(209, 'French Guiana'),
(210, 'French Polynesia'),
(61, 'Gabon'),
(62, 'Gambia'),
(63, 'Georgia'),
(64, 'Germany'),
(65, 'Ghana'),
(211, 'Gibraltar'),
(66, 'Greece'),
(212, 'Greenland'),
(67, 'Grenada'),
(213, 'Guam'),
(68, 'Guatemala'),
(69, 'Guinea'),
(70, 'Guinea-Bissau'),
(71, 'Guyana'),
(72, 'Haiti'),
(73, 'Honduras'),
(74, 'Hungary'),
(75, 'Iceland'),
(76, 'India'),
(77, 'Indonesia'),
(80, 'Ireland'),
(81, 'Israel'),
(82, 'Italy'),
(83, 'Jamaica'),
(84, 'Japan'),
(85, 'Jordan'),
(86, 'Kazakhstan'),
(87, 'Kenya'),
(88, 'Kiribati'),
(90, 'Korea, South'),
(91, 'Kuwait'),
(92, 'Kyrgyzstan'),
(93, 'Laos'),
(94, 'Latvia'),
(95, 'Lebanon'),
(96, 'Lesotho'),
(97, 'Liberia'),
(98, 'Libya'),
(99, 'Liechtenstein'),
(100, 'Lithuania'),
(101, 'Luxembourg'),
(195, 'Macao SAR'),
(102, 'Macedonia'),
(103, 'Madagascar'),
(104, 'Malawi'),
(105, 'Malaysia'),
(106, 'Maldives'),
(107, 'Mali'),
(108, 'Malta'),
(109, 'Marshall Islands'),
(110, 'Mauritania'),
(111, 'Mauritius'),
(215, 'Mayotte'),
(112, 'Mexico'),
(113, 'Moldova'),
(114, 'Monaco'),
(115, 'Mongolia'),
(217, 'Montserrat'),
(116, 'Morocco'),
(117, 'Mozambique'),
(119, 'Namibia'),
(120, 'Nauru'),
(121, 'Nepal'),
(122, 'Netherlands'),
(218, 'Netherlands Antilles'),
(219, 'New Caledonia'),
(123, 'New Zealand'),
(124, 'Nicaragua'),
(125, 'Niger'),
(126, 'Nigeria'),
(220, 'Niue'),
(221, 'Norfolk Island'),
(222, 'Northern Mariana Islands'),
(127, 'Norway'),
(128, 'Oman'),
(129, 'Pakistan'),
(130, 'Palau'),
(235, 'Palestine'),
(131, 'Panama'),
(132, 'Papua New Guinea'),
(133, 'Paraguay'),
(134, 'Peru'),
(135, 'Philippines'),
(223, 'Pitcairn'),
(136, 'Poland'),
(137, 'Portugal'),
(191, 'Puerto Rico'),
(138, 'Qatar'),
(224, 'Reunion'),
(139, 'Romania'),
(140, 'Russia'),
(141, 'Rwanda'),
(144, 'Saint Vincent & the Grenadines'),
(145, 'Samoa'),
(146, 'San Marino'),
(147, 'Sao Tome and Principe'),
(148, 'Saudi Arabia'),
(149, 'Senegal'),
(187, 'Serbia and Montenegro (former Yugoslavia)'),
(150, 'Seychelles'),
(151, 'Sierra Leone'),
(152, 'Singapore'),
(153, 'Slovakia'),
(154, 'Slovenia'),
(155, 'Solomon Islands'),
(156, 'Somalia'),
(157, 'South Africa'),
(226, 'South Georgia'),
(158, 'Spain'),
(159, 'Sri Lanka'),
(142, 'St. Kitts and Nevis'),
(143, 'St. Lucia'),
(229, 'St. Pierre and Miquelon'),
(161, 'Suriname'),
(162, 'Swaziland'),
(163, 'Sweden'),
(164, 'Switzerland'),
(166, 'Taiwan'),
(167, 'Tajikistan'),
(168, 'Tanzania'),
(169, 'Thailand'),
(170, 'Togo'),
(230, 'Tokelau'),
(171, 'Tonga'),
(172, 'Trinidad & Tobago'),
(173, 'Tunisia'),
(174, 'Turkey'),
(175, 'Turkmenistan'),
(231, 'Turks and Caicos Islands'),
(176, 'Tuvalu'),
(177, 'Uganda'),
(178, 'Ukraine'),
(179, 'United Arab Emirates'),
(181, 'Uruguay'),
(182, 'Uzbekistan'),
(183, 'Vanuatu'),
(184, 'Venezuela'),
(185, 'Vietnam'),
(232, 'Virgin Islands (U.K.)'),
(233, 'Virgin Islands (U.S.)'),
(234, 'Wallis and Futuna Islands'),
(186, 'Yemen'),
(188, 'Zaire'),
(189, 'Zambia');

insert ms_sugar_user(fb_uid) values();

