application: deonwu84
version: 5
runtime: python
api_version: 1

handlers:
- url: /admin/.*
  script: $PYTHON_LIB/apphosting/ext/admin/

- url: /static
  static_dir: static

- url: /.*
  script: mysite_dispatcher.py